//
// Created by RGAA on 27/02/2025.
//

#ifndef GAMMARAY_MGR_DEVICE_H
#define GAMMARAY_MGR_DEVICE_H

#include <memory>
#include <string>
#include "json/json.hpp"

using namespace nlohmann;

namespace spvr
{

    const std::string kData = "data";
    const std::string kDeviceId = "device_id";
    const std::string kDeviceName = "device_name";
    const std::string kDeviceLoggedInUser = "logged_in_user_id";
    const std::string kDeviceSeed = "seed";
    const std::string kDeviceRandomPwd = "random_pwd_md5";
    const std::string kDeviceSafetyPwd = "safety_pwd_md5";
    const std::string kDeviceDeleted = "deleted";
    const std::string kDeviceCreatedTimestamp = "created_timestamp";
    const std::string kDeviceUpdatedTimestamp = "last_update_timestamp";
    const std::string kUsedTime = "used_time";
    const std::string kGenRandomPwd = "gen_random_pwd";
    const std::string kDeviceDesktopLink = "desktop_link";
    const std::string kDeviceDesktopLinkRaw = "desktop_link_raw";
    const std::string kDeviceActive = "active";
    const std::string kDeviceIp = "device_ip";

    class SpvrDevice {
    public:
        // obj["xx"]
        static std::shared_ptr<SpvrDevice> FromJson(const std::string& body);

        // obj["xx"]
        static std::shared_ptr<SpvrDevice> FromObj(const json& obj);

        // dump
        std::string Dump();

    public:
        // 9 numbers
        std::string device_id_;
        // device name
        std::string device_name_;
        // user id
        std::string logged_in_user_id_;
        // generated by
        std::string seed_;
        // created
        int64_t created_timestamp_{0};
        // updated.
        int64_t last_update_timestamp_{0};
        // random password
        std::string random_pwd_md5_;
        // safety password
        std::string safety_pwd_md5_;
        // used time ; unit: ms
        int64_t used_time_{0};
        // random pwd
        std::string gen_random_pwd_;
        //
        std::string desktop_link_;
        //
        std::string desktop_link_raw_;
        // active
        bool active_{true};
    };

}

#endif //GAMMARAY_MGR_DEVICE_H
