//
// Created by RGAA on 27/02/2025.
//

#ifndef GAMMARAY_MGR_DEVICE_H
#define GAMMARAY_MGR_DEVICE_H

#include <string>

namespace spvr
{

    const std::string kMgrDeviceBid = "bid";
    const std::string kMgrDeviceId = "device_id";
    const std::string kMgrDeviceBelongToUser = "belong_to_user";
    const std::string kMgrDeviceSeed = "seed";
    const std::string kMgrDeviceRandomPwd = "random_pwd";
    const std::string kMgrDeviceSafetyPwd = "safety_pwd";
    const std::string kMgrDeviceDeleted = "deleted";
    const std::string kMgrDeviceCreatedTimestamp = "created_timestamp";
    const std::string kMgrDeviceUpdatedTimestamp = "updated_timestamp";
    const std::string kMgrUsedTime = "used_time";

    class SpvrDevice {
    public:
        std::string obj_id_{};
        // 9 numbers
        std::string device_id_;
        // user id
        std::string belong_to_user_;
        // generated by
        std::string seed_;
        // random pwd
        std::string gen_random_pwd_;
        // random password
        std::string random_pwd_md5_;
        // safety password
        std::string safety_pwd_md5_;
        // 0 -> alive
        // 1 -> deleted
        int deleted_{0};
        // created
        int64_t created_timestamp_{0};
        // updated.
        int64_t updated_timestamp_{0};
        // used time ; unit: ms
        int64_t used_time_{0};
    };

}

#endif //GAMMARAY_MGR_DEVICE_H
